package com.culcom.entity.enums;

public enum ActivityEventType {
    ATTENDANCE,
    STATUS_CHANGE,
    CLASS_ASSIGN,
    INFO_CHANGE,
    REFUND_CHANGE,
    MEMBER_CREATE,
    MEMBERSHIP_ASSIGN,
    MEMBERSHIP_UPDATE,
    MEMBERSHIP_DELETE,
    MEMBERSHIP_CHANGE,
    PAYMENT_ADD,
    PAYMENT_REFUND,
    POSTPONEMENT_REQUEST,
    POSTPONEMENT_APPROVE,
    POSTPONEMENT_REJECT,
    REFUND_REQUEST,
    REFUND_APPROVE,
    REFUND_REJECT,
    TRANSFER_OUT,
    TRANSFER_IN,
    TRANSFER_REQUEST,
    TRANSFER_REJECT
}
