package com.culcom.entity.enums;

public enum ActivityEventType {
    ATTENDANCE,
    STATUS_CHANGE,
    CLASS_ASSIGN,
    INFO_CHANGE,
    REFUND_CHANGE,
    MEMBER_CREATE,
    MEMBERSHIP_ASSIGN,
    MEMBERSHIP_UPDATE,
    MEMBERSHIP_DELETE,
    POSTPONEMENT_REQUEST,
    POSTPONEMENT_APPROVE,
    POSTPONEMENT_REJECT,
    REFUND_REQUEST,
    REFUND_APPROVE,
    REFUND_REJECT
}
